name: Clone Repository to Self-hosted Windows Machine of Kuslum

on:
  push:
    branches:
      - main # change this to the name of the branch you want to clone

jobs:
  clone:
    runs-on: [self-hosted, kulsum] # specify the label of your self-hosted runner here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
